### ISSUE TITLE
Support for altered chords

### ISSUE THREAD

**Issue by Marr11317** [no-chris/chord-symbol#230]
It looks like `alt` or `alt.` as a modifier is not supported.

Even though it looks like a maybe broad modifier, there might still be a way for the renderer to parse it. It could, for instance, be translated into `7(b5b9#9#11b13)` or simply `7(b5b9b13)` or even `7(#9#11)`.

I would personnally opt for the fully-fledged `7(b5b9#9#11b13)`

**Comment by no-chris** [comment]
Interesting one.

Since it's a modifier opened for interpretation, another option could be to pass it as such and render it as `alt`, rather than enforcing a specific interpretation, wdyt?

**Comment by no-chris** [comment]
I'm a bit reluctant to enforce a specific interpretation of the intervals covered by the `alt` modifier, since it is, by definition, opened to interpretation. 

In order to make a decision, could you please explain your use case so I get a broader view of the issue?

**Comment by Marr11317** [comment]
I am basically using your library to know which degrees to use when doing a walking bass and some piano comping. It's of course fairly simple, but the alt. modifier comes up quite often in jazz, and I
 1) can't render it on screen yet and
 2) can't parse its degrees

I could, of course, filter it before sending it to your library, but I thought it might as well be part of it.
I'll try to dip in the code today.

**Comment by no-chris** [comment]
>I would personally opt for the fully-fledged 7(b5b9#9#11b13)

On which rationale?

And if one enters `7(b5b9#9#11b13)` would you expect it to be rendered as `alt.`?
What would be the result of parsing `C9alt.`?

Just exploring ideas, we could allow some degrees of configuration here, from 0 intervals parsing, just parsing and rendering the string `alt` to some specific intervals parsing

**Comment by Marr11317** [comment]
see #236
