### ISSUE TITLE
Allow more rendering options

### ISSUE THREAD

**Issue by Marr11317** [no-chris/chord-symbol#290]
In [bb-format](https://github.com/Marr11317/bb-format), I wanted to render minor chords as with a "-" instead of a "mi" so I added a search-and-replace for it.
![image](https://user-images.githubusercontent.com/35939574/97068341-912e3600-1594-11eb-952f-2addcb383c7b.png)

However, it is not the only that might want to have even shorter options (like Delta for Maj7), I thought I might as well add these options directly in this lib instead of post-processing it.

So here's the question: how should that be done? Should I:
- add another "shortnamings" option? (this would mean changing shortnamings from a bool to an enum containing something like "academic", "short", "usingSymbols". 
- add a "useDashInsteadOfMiForMinor" option (with a better name). But then what about the delta for major7? Another option? We might end up with too many options like these.
- keep the post processing, but make it easier to add post process hooks (custom processing/parsing/rendering rules)
- anything else that seems more sensible?

Thanks

**Comment by no-chris** [comment]
Wow, that looks amazing! Great job 👏 

Option 3 is preferred to keep the API clean. It's actually a feature I wanted to add for some time and I've been working on it during the last few days: https://github.com/no-chris/chord-symbol/pull/292

The idea here would be to add a rendering filter to customise the rendering to your taste. You could either:
- implement your own version of https://github.com/no-chris/chord-symbol/blob/master/src/parser/filters/formatSymbolParts.js 
- just search/replace the parts that you want to change in the `formatted` object.

That was the initial idea behind the library: there is an opinionated default rendering, but the normalised chord object allows a user to bypass it and tailor every part of the rendering as he prefers

Would this cover your need?

**Comment by Marr11317** [comment]
Ok, seems perfect! Then I'll use #292.

**Comment by no-chris** [comment]
You can use directly the v1.1.0 branch

Let me know if it works fine so we can close the issue.

**Comment by Marr11317** [comment]
Works as a charm.

**Comment by no-chris** [comment]
Great ! Let's release then! 🚀
