### ISSUE TITLE
Many links are broken

### ISSUE THREAD

**Issue by nashirj** [no-chris/chord-symbol#576]
Hi Christophe, thanks for making this incredible project. I noticed that many links (e.g. the link to the API documentation on https://chord-symbol.netlify.app/, the link to modifiers.js in /chord-symbol/packages/chord-symbol/README.md) are broken and am creating this issue to let you know. In both of these cases, adding `/packages/chord-symbol` after the initial `chord-symbol` in the link fixes the issue.

**Comment by no-chris** [comment]
Hello,
Thanks for pointing that out
Indeed many links got broken after the monorepo migration and I haven't fixed them yet
Will try to do asap
Thanks again

**Comment by no-chris** [comment]
Fixed in https://github.com/no-chris/chord-symbol/commit/e1e638c0c3a950b3eda78caf52bb3c0b4b11bed1 and https://github.com/no-chris/chord-symbol-demo/commit/48be20848c933baea65bada14200485d525369f6
