### ISSUE TITLE
Types files are out of date

### ISSUE THREAD

**Issue by darrylnoakes** [no-chris/chord-symbol#593]
The `src/typedefs.js` file and the `types/index.d.ts` file are out of sync. The TS one is out of date.

For example, `FormattedChord` has no `symbol` property, and the chord renderer factory config still uses the `useFlats` options instead of `accidentals`.

I am using/looking at the v4 beta.

**Comment by no-chris** [comment]
Right, I keep on forgetting about updating those on new releases. Thanks for pointing this out.
