### ISSUE TITLE
Chords like A7+5 is parsed incorrectly

### ISSUE THREAD

**Issue by perivar** [no-chris/chord-symbol#609]
A7+5 is incorrectly parsed into A5, the same is A7(+5) instead of A7(#5).
However A7+ is correctly parsed into A7(#5).
The same error applies to A7-5, which is parsed into A5, instead of A7(b5).

My fix which seem to work for now is:
let valueCleaned = value;
valueCleaned = valueCleaned.replace(/\+5/g, '(#5)');
valueCleaned = valueCleaned.replace(/\-5/g, '(b5)');

**Comment by no-chris** [comment]
Thanks for the report!
This will be fixed in `4.0.0`

**Comment by no-chris** [comment]
Available in [v4.0.0-beta.4](https://github.com/no-chris/chord-symbol/releases/tag/v4.0.0-beta.4)
