### ISSUE TITLE
German notation does not support bass notes with b or #

### ISSUE THREAD

**Issue by perivar** [no-chris/chord-symbol#611]
It seems no bass notes with # or b works with german notation.
The chord H7/F# does not work.
Neither does H/Db.

For actual example, check out this tab
[https://nortabs.net/tab/944/](url)

**Comment by no-chris** [comment]
Hello,
That is because the parser expect accidentals to be given as `is` or `es`
So even `F#` as a chord does not work.
It looks like more flexibility would be needed?
Thanks

**Comment by no-chris** [comment]
That's easy enough to add if you tell me it is needed https://github.com/no-chris/chord-symbol/pull/614
