### ISSUE TITLE
Question: How would you get all notes back for a chord with bass

### ISSUE THREAD

**Issue by perivar** [no-chris/chord-symbol#612]
How would you get back all notes when you parse a chord with a bass note?

E.g. the Chord DMaj7/G contain only the Dmaj7 notes in the notes array. The G is not included.

input": {
    "symbol": "DMAJ7/G",
  },
    "notes": [
      "D",
      "F#",
      "A",
      "C#"
    ]

**Comment by no-chris** [comment]
Well if it's an inversion then the bass is already part of the chord, e.g. `C/E` => `C, E, G`

If it's not an inversion then I wouldn't expect it to be in the `notes` array, but you can get it from the `normalized.bassNote` property

Does that makes sense?

Thanks

**Comment by perivar** [comment]
Yes thank you.
