### ISSUE TITLE
UltimateGuitar replace entries will likely fail for several entries?!

### ISSUE THREAD

**Issue by perivar** [no-chris/chord-symbol#618]
I believe the current replace entries will fail in several instances.

An updated version I use is:
const chordSymbolUltimateGuitarRenderer = (chord: any) => {
  chord.formatted.symbol = chord.formatted.symbol
    .replace(/[(), ]/g, '')
    .replace(/mM(?!aj)/g, 'mMaj')
    .replace(/M(?!aj)/g, 'Maj')
    .replace('°', 'dim');

  return chord;
};

**Comment by no-chris** [comment]
Nice! Would you mind doing a pull request with the fix and updated tests cases that would be failing today?  🙏

**Comment by perivar** [comment]
I will look at this later. I did not find any immediate errors trying our more chords so I might have been to quick believing these changes are necessary....
I'll get back to this :)

**Comment by no-chris** [comment]
No worries, let's keep this open just in case

**Comment by no-chris** [comment]
closing since no actual case has been submitted
