### ISSUE TITLE
add new feature to demo: display the chord fingering for piano

### ISSUE THREAD

**Issue by jutunen** [no-chris/chord-symbol#82]
Hello!

Adding chord fingering for piano will be trivial with this web component:

https://github.com/jutunen/custom-piano-keys

regards,
Jussi

**Comment by no-chris** [comment]
Great job, congrats! 

Won't have time to work on it right away but that's a cool idea. If you feel like it, feel free to submit a PR. Note that the reverse is possible as well, you could include this lib on your demo site to have an alternate way of entering intervals.

Thanks for dropping by!
